[versions]
pluginYml = "0.8.0"
purpurApi = "1.21.11-R0.1-SNAPSHOT"
griefPrevention = "17.0.0"

[libraries]
purpurApi = { group = "org.purpurmc.purpur", name = "purpur-api", version.ref = "purpurApi" }
griefPrevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref  = "griefPrevention" }

[plugins]
pluginYml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYml" }
